name: Build and publish to PyPI

on:
  push:
    tags:
      - 'v*'                 # 例: v0.3.0 を push すると発火

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # ❶ リポジトリ & サブモジュールを取得
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive   # Eigen を含めすべて取得
        fetch-depth: 0          # タグ参照用に履歴を完全取得

    # ❷ Python 3.11 をセットアップ
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # ❸ 最新 pip & build ユーティリティ
    - name: Upgrade pip and install build
      run: python -m pip install --upgrade pip build

    # ❹ cibuildwheel をインストール
    - name: Install cibuildwheel
      run: pip install cibuildwheel==2.23.3

    # ❺ x86_64 ＋ aarch64 wheel をビルド
    - name: Build wheels
      env:
        CIBW_ARCHS_LINUX: "x86_64 aarch64"   # ← aarch64 を追加
        CIBW_SKIP: "pp*"                     # PyPy はスキップ
        CIBW_BUILD_VERBOSITY: "1"            # ログ詳細 (任意)
      run: cibuildwheel --output-dir dist

    # ❻ ソース配布 (sdist) も生成
    - name: Build sdist
      run: python -m build --sdist -o dist

    # ❼ PyPI へアップロード
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
