name: Build and publish to PyPI

on:
  push:
    tags:
      - 'v*'  # v1.0.0 などのタグが push されたとき

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.23.3

      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: >
            yum install -y epel-release &&
            yum install -y python3-devel eigen3-devel
        run: cibuildwheel --output-dir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
